name: movies_movil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  visibility_detector: ^0.4.0+2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
   - .env
